version: '3.7'

services:
  api:
    image: "fastapi_starter:1.0.0"
    container_name: "fastapi_starter"
    depends_on:
      - db
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - ./app:/usr/src/app/app:cached
      - ./db:/usr/src/app/db:cached
      - ./scripts/dev:/usr/src/app/scripts/dev:cached
    working_dir: /usr/src/app/scripts/dev
    command: bash -c "chmod +x ./run.sh && ./run.sh"
    networks:
      - fastapi_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development

  db:
    image: "fastapi_starter_db:0.1.0"
    container_name: "fastapi_starter_db"
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    tty: true
    expose:
      - "3306"
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d:cached
      - ./log/db:/var/log/mysql:cached
      - ./db-store:/var/lib/mysql
    networks:
      - fastapi_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development
  
  web:
    container_name: nginx
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    depends_on:
      - api
    env_file:
      - .env.development
    volumes:
      - ./static:/static
    networks:
      - fastapi_network
  
networks:
  default:
    external:
      name: bridge
  fastapi_network:
    name: fastapi_network
    driver: bridge
    external: true
